package controller;


public enum CommandName {
    CREATE_NOTE_BOOK_COMMAND, ADD_NOTE_COMMAND, FIND_NOTE_ON_CONTENT_COMMAND, FIND_NOTE_ON_DATE_COMMAND,
    LOAD_NOTE_BOOK_ON_FILE, SHOW_NOTE_IN_NOTE_BOOK_COMMAND, WRITE_NOTE_BOOK_IN_FILE_COMMAND
}
